# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d2742498d55eb18bba6d76e033cfa70ef49306e591f0a1b076c20a64eacb7bd1439c3889aa7051b381180690639760e9176c2ab8e8edc1a4fb8affa5726590e

test:
  secret_key_base: cca64e7333e2043ae81f9e7f43a176e3cc29b3ad2d21087c0e2e189d9f7755ddc29de6a7d6e037b89b4b916867d6a73c16d3885c2e661f04054b07852f6f6161

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
